# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.12
repos:
-   repo: local
    hooks:
    -   id: ruff
        name: ruff
        language: system
        files: '^classes2/.*'
        entry: bash -c 'cd classes2 && ruff . --fix --exit-non-zero-on-fix'
-   repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: bash -c 'cd classes2 && pytest'
        language: system
        pass_filenames: false
        always_run: true
